ALTER TABLE shops ADD COLUMN IF NOT EXISTS totp_secret VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS totp_enabled BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE system_admins ADD COLUMN IF NOT EXISTS totp_secret VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE system_admins ADD COLUMN IF NOT EXISTS totp_enabled BOOLEAN NOT NULL DEFAULT false;
